"""
crystaldiskmark_parser is a Python library for reading in
the .txt files generated by CrystalDiskMark in Python
"""

__version__ = "1.0.4"
from .parser import parse, parse_df, convert_cdm7_result_encoding