# Test Python Package
#
# Source: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Python Package

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-n-test:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install package dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f setup.py ]; then pip install .; fi

      - name: Unit test package
        run: >-
          python -m
          unittest discover test/
      
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build

      - name: Build package
        run: python -m build
